### ISSUE TITLE
Hardcoded selected database and table definitions

### ISSUE THREAD

**Issue by Frier03** [Syncora/Syncora-Backend#4]
The current implementation in the file `setup.js` hardcodes the selected database and table definitions. Dont do that! In the future, scalability is limited to this code.

Affected File: `src/database/tables/setup.js`

https://github.com/Syncora/Syncora-Backend/blob/01141ef8e1bce1c151eb7e79b783dc6215417e64/src/database/tables/setup.js#L42-L61

**Comment by Mikkel-Coder** [comment]
hummm

**Comment by Frier03** [comment]
Still active.

**Comment by Frier03** [comment]
Improved code at commit: https://github.com/Syncora/Syncora-Backend/commit/2422cc104d75cbf08d9cd37ce00c733d4ae16d0c
